[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."api/wordware/route"]
  included_files = ["src/lib/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]
  timeout = 300
