[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["src/**"]

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
